import { Presets } from "lynx-pulsar";

export interface PresetMeta {
  name: string;
  description: string;
  tags: string[];
  duration: number;
  play: () => void;
}

export const SYSTEM_PRESETS: PresetMeta[] = [
  { name: "ImpactLight", description: "Light impact feedback", tags: ["System"], duration: 0, play: Presets.System.impactLight },
  { name: "ImpactMedium", description: "Medium impact feedback", tags: ["System"], duration: 0, play: Presets.System.impactMedium },
  { name: "ImpactHeavy", description: "Heavy impact feedback", tags: ["System"], duration: 0, play: Presets.System.impactHeavy },
  { name: "ImpactSoft", description: "Soft impact feedback", tags: ["System"], duration: 0, play: Presets.System.impactSoft },
  { name: "ImpactRigid", description: "Rigid impact feedback", tags: ["System"], duration: 0, play: Presets.System.impactRigid },
  { name: "NotificationSuccess", description: "Success notification", tags: ["System"], duration: 0, play: Presets.System.notificationSuccess },
  { name: "NotificationWarning", description: "Warning notification", tags: ["System"], duration: 0, play: Presets.System.notificationWarning },
  { name: "NotificationError", description: "Error notification", tags: ["System"], duration: 0, play: Presets.System.notificationError },
  { name: "Selection", description: "Selection change tick", tags: ["System"], duration: 0, play: Presets.System.selection },
];

export const CUSTOM_PRESETS: PresetMeta[] = [
  { name: "Afterglow", description: "A three-beat phrase that dissolves gently, ideal for soft endings or gradually quieting feedback.", tags: ["Bold", "Soft", "Impulses", "Short"], duration: 150, play: Presets.afterglow },
  { name: "Aftershock", description: "A firm opening that settles calmly, ideal for transitions needing a strong start and a gentle finish.", tags: ["Substantial", "Flexible", "Impulses", "Extended"], duration: 500, play: Presets.aftershock },
  { name: "Alarm", description: "Relentless and urgent, best for critical errors or emergencies that require immediate attention.", tags: ["Bold", "Rigid", "Pattern", "Extended"], duration: 1130, play: Presets.alarm },
  { name: "Anvil", description: "The full weight of a massive collision, conveys sheer physical force and momentum.", tags: ["Bold", "Soft", "Ramp", "Extended"], duration: 500, play: Presets.anvil },
  { name: "Applause", description: "A growing wave of appreciation, ideal for celebratory moments or social approval.", tags: ["Substantial", "Flexible", "Solid", "Long"], duration: 1564, play: Presets.applause },
  { name: "Ascent", description: "The rush of leveling up, evoking the classic RPG reward of growth and progression.", tags: ["Bold", "Flexible", "Pattern", "Long"], duration: 2400, play: Presets.ascent },
  { name: "BalloonPop", description: "Mounting suspense that bursts into release, perfect for countdowns or suspenseful reveals.", tags: ["Substantial", "Flexible", "Bumps", "Long"], duration: 1700, play: Presets.balloonPop },
  { name: "Barrage", description: "An overwhelming storm of rapid impacts.", tags: ["Bold", "Rigid", "Impulses", "Extended"], duration: 309, play: Presets.barrage },
  { name: "BassDrop", description: "Two grounded thumps with a tonal descent.", tags: ["Bold", "Soft", "Impulses", "Impulse"], duration: 71, play: Presets.bassDrop },
  { name: "Batter", description: "An unrestrained explosion of rage.", tags: ["Bold", "Flexible", "Saw", "Extended"], duration: 380, play: Presets.batter },
  { name: "BellToll", description: "Three notes that soften as they land.", tags: ["Bold", "Flexible", "Impulses", "Extended"], duration: 399, play: Presets.bellToll },
  { name: "Blip", description: "A composed, subtle heads-up.", tags: ["Gentle", "Flexible", "Peak", "Short"], duration: 200, play: Presets.blip },
  { name: "Bloom", description: "A quiet confirmation of completion.", tags: ["Gentle", "Flexible", "Bumps", "Extended"], duration: 300, play: Presets.bloom },
  { name: "Bongo", description: "Two balanced bursts of three.", tags: ["Substantial", "Flexible", "Impulses", "Extended"], duration: 451, play: Presets.bongo },
  { name: "Boulder", description: "Deep and weighty without sharpness.", tags: ["Bold", "Soft", "Impulses", "Impulse"], duration: 0, play: Presets.boulder },
  { name: "BreakingWave", description: "Two measured steps leading into a stronger landing.", tags: ["Substantial", "Flexible", "Impulses", "Short"], duration: 202, play: Presets.breakingWave },
  { name: "Breath", description: "Slow, calming in-and-out rhythm.", tags: ["Substantial", "Soft", "Bumps", "Long"], duration: 3200, play: Presets.breath },
  { name: "Buildup", description: "An energizing crescendo of rising intensity.", tags: ["Bold", "Flexible", "Impulses", "Extended"], duration: 309, play: Presets.buildup },
  { name: "Burst", description: "The tension-and-release of a sneeze.", tags: ["Bold", "Flexible", "Peak", "Extended"], duration: 300, play: Presets.burst },
  { name: "Buzz", description: "An unmistakable hard rejection.", tags: ["Bold", "Rigid", "Ramp", "Extended"], duration: 350, play: Presets.buzz },
  { name: "Cadence", description: "A natural two-beat rhythm.", tags: ["Bold", "Rigid", "Impulses", "Short"], duration: 199, play: Presets.cadence },
  { name: "CameraShutter", description: "The satisfying click of capturing a moment.", tags: ["Substantial", "Rigid", "Impulses", "Short"], duration: 150, play: Presets.cameraShutter },
  { name: "Canter", description: "A three-beat rhythm with natural variation.", tags: ["Bold", "Soft", "Impulses", "Short"], duration: 173, play: Presets.canter },
  { name: "Cascade", description: "A long sequence that unwinds from intensity to calm.", tags: ["Substantial", "Flexible", "Impulses", "Long"], duration: 1863, play: Presets.cascade },
  { name: "Castanets", description: "A crisp, decisive pair of sharp taps.", tags: ["Bold", "Rigid", "Impulses", "Short"], duration: 199, play: Presets.castanets },
  { name: "CatPaw", description: "A calm, warm pair of taps.", tags: ["Substantial", "Soft", "Impulses", "Impulse"], duration: 75, play: Presets.catPaw },
  { name: "Charge", description: "The electric buildup of a countdown.", tags: ["Bold", "Rigid", "Pattern", "Long"], duration: 2046, play: Presets.charge },
  { name: "Chime", description: "A warm, friendly double-tap.", tags: ["Substantial", "Flexible", "Bumps", "Extended"], duration: 380, play: Presets.chime },
  { name: "Chip", description: "Sharp, authoritative, and precise.", tags: ["Substantial", "Rigid", "Impulses", "Impulse"], duration: 0, play: Presets.chip },
  { name: "Chirp", description: "Light-hearted and cheerful.", tags: ["Gentle", "Flexible", "Saw", "Extended"], duration: 360, play: Presets.chirp },
  { name: "Clamor", description: "Impossible to ignore, suited for critical warnings.", tags: ["Bold", "Flexible", "Saw", "Extended"], duration: 430, play: Presets.clamor },
  { name: "Clasp", description: "The satisfying snap of acquiring a target.", tags: ["Bold", "Rigid", "Impulses", "Short"], duration: 220, play: Presets.clasp },
  { name: "Cleave", description: "Signals an irreversible, high-stakes action.", tags: ["Bold", "Rigid", "Impulses", "Short"], duration: 250, play: Presets.cleave },
  { name: "Coil", description: "Rising tension that releases into certainty.", tags: ["Substantial", "Flexible", "Peak", "Long"], duration: 650, play: Presets.coil },
  { name: "CoinDrop", description: "A playful cascade of coins.", tags: ["Bold", "Rigid", "Saw", "Extended"], duration: 675, play: Presets.coinDrop },
  { name: "CombinationLock", description: "The ritual of cracking a code.", tags: ["Bold", "Rigid", "Saw", "Long"], duration: 980, play: Presets.combinationLock },
  { name: "Crescendo", description: "A rising build that peaks with energy.", tags: ["Substantial", "Rigid", "Impulses", "Long"], duration: 601, play: Presets.crescendo },
  { name: "Dewdrop", description: "A quiet confirmation of success.", tags: ["Substantial", "Flexible", "Bumps", "Short"], duration: 210, play: Presets.dewdrop },
  { name: "Dirge", description: "Heavy and fading like a dying heartache.", tags: ["Substantial", "Soft", "Pattern", "Long"], duration: 2600, play: Presets.dirge },
  { name: "Dissolve", description: "A gentle, soothing fade.", tags: ["Gentle", "Soft", "Ramp", "Long"], duration: 1200, play: Presets.dissolve },
  { name: "DogBark", description: "Two forceful low bursts like a sharp bark.", tags: ["Bold", "Soft", "Bumps", "Extended"], duration: 500, play: Presets.dogBark },
  { name: "Drone", description: "Flat and going nowhere.", tags: ["Gentle", "Flexible", "Pattern", "Long"], duration: 1780, play: Presets.drone },
  { name: "EngineRev", description: "The thrill of revving to full throttle.", tags: ["Bold", "Flexible", "Bumps", "Long"], duration: 1800, play: Presets.engineRev },
  { name: "Exhale", description: "Tension releasing into calm.", tags: ["Substantial", "Flexible", "Ramp", "Long"], duration: 1200, play: Presets.exhale },
  { name: "Explosion", description: "A catastrophic detonation that echoes into rumble.", tags: ["Bold", "Soft", "Ramp", "Long"], duration: 1000, play: Presets.explosion },
  { name: "FadeOut", description: "A graceful drift toward silence.", tags: ["Substantial", "Flexible", "Impulses", "Extended"], duration: 506, play: Presets.fadeOut },
  { name: "Fanfare", description: "A short burst of triumph.", tags: ["Bold", "Rigid", "Bumps", "Extended"], duration: 580, play: Presets.fanfare },
  { name: "Feather", description: "A gentle, non-disruptive nudge.", tags: ["Substantial", "Flexible", "Ramp", "Short"], duration: 180, play: Presets.feather },
  { name: "Finale", description: "A countdown that closes with emphasis.", tags: ["Bold", "Flexible", "Bumps", "Long"], duration: 680, play: Presets.finale },
  { name: "FingerDrum", description: "Three casual, even taps.", tags: ["Substantial", "Flexible", "Impulses", "Extended"], duration: 231, play: Presets.fingerDrum },
  { name: "Firecracker", description: "Two maximum-force strikes.", tags: ["Bold", "Rigid", "Impulses", "Impulse"], duration: 75, play: Presets.firecracker },
  { name: "Fizz", description: "Bubbling with joy.", tags: ["Substantial", "Rigid", "Saw", "Extended"], duration: 500, play: Presets.fizz },
  { name: "Flare", description: "A mind-blowing jolt.", tags: ["Bold", "Rigid", "Peak", "Extended"], duration: 380, play: Presets.flare },
  { name: "Flick", description: "A light, quick tap with minimal presence.", tags: ["Gentle", "Flexible", "Peak", "Impulse"], duration: 80, play: Presets.flick },
  { name: "Flinch", description: "A shock to the senses.", tags: ["Bold", "Flexible", "Bumps", "Extended"], duration: 280, play: Presets.flinch },
  { name: "Flourish", description: "Triumphant and expansive.", tags: ["Bold", "Rigid", "Peak", "Long"], duration: 917, play: Presets.flourish },
  { name: "Flurry", description: "The thrill of a combo streak.", tags: ["Bold", "Rigid", "Bumps", "Extended"], duration: 300, play: Presets.flurry },
  { name: "Flush", description: "The involuntary heave of disgust.", tags: ["Bold", "Flexible", "Peak", "Extended"], duration: 380, play: Presets.flush },
  { name: "Gallop", description: "A natural four-beat rhythm.", tags: ["Bold", "Flexible", "Impulses", "Long"], duration: 750, play: Presets.gallop },
  { name: "Gavel", description: "Two weighty, deliberate taps.", tags: ["Bold", "Flexible", "Impulses", "Short"], duration: 201, play: Presets.gavel },
  { name: "Glitch", description: "The haptic feel of a system glitching.", tags: ["Bold", "Rigid", "Pattern", "Short"], duration: 220, play: Presets.glitch },
  { name: "GuitarStrum", description: "A rich, resonant strike that lingers.", tags: ["Bold", "Flexible", "Ramp", "Long"], duration: 1400, play: Presets.guitarStrum },
  { name: "Hail", description: "An unpredictable, relentless barrage.", tags: ["Gentle", "Rigid", "Solid", "Extended"], duration: 430, play: Presets.hail },
  { name: "Hammer", description: "The insistent urgency of a fist on a door.", tags: ["Bold", "Soft", "Saw", "Long"], duration: 1050, play: Presets.hammer },
  { name: "Heartbeat", description: "The familiar lub-dub of life and tension.", tags: ["Substantial", "Soft", "Pattern", "Long"], duration: 1000, play: Presets.heartbeat },
  { name: "Herald", description: "Two gentle knocks building to a decisive third.", tags: ["Substantial", "Rigid", "Impulses", "Short"], duration: 208, play: Presets.herald },
  { name: "HoofBeat", description: "Two warm, grounded taps.", tags: ["Bold", "Soft", "Impulses", "Short"], duration: 201, play: Presets.hoofBeat },
  { name: "Ignition", description: "Three beats that sharpen with each hit.", tags: ["Bold", "Flexible", "Impulses", "Short"], duration: 173, play: Presets.ignition },
  { name: "Impact", description: "The instant punch of impact.", tags: ["Bold", "Flexible", "Peak", "Short"], duration: 200, play: Presets.impact },
  { name: "Jolt", description: "The most intense hit possible.", tags: ["Bold", "Rigid", "Impulses", "Impulse"], duration: 0, play: Presets.jolt },
  { name: "KeyboardMechanical", description: "The satisfying snap of a mechanical key.", tags: ["Gentle", "Flexible", "Impulses", "Impulse"], duration: 55, play: Presets.keyboardMechanical },
  { name: "KeyboardMembrane", description: "A soft, muffled press.", tags: ["Gentle", "Soft", "Impulses", "Short"], duration: 140, play: Presets.keyboardMembrane },
  { name: "Knell", description: "A commanding last-chance signal.", tags: ["Bold", "Flexible", "Bumps", "Extended"], duration: 550, play: Presets.knell },
  { name: "Knock", description: "A polite knock announcing arrival.", tags: ["Substantial", "Soft", "Bumps", "Long"], duration: 760, play: Presets.knock },
  { name: "Lament", description: "The sinking finality of defeat.", tags: ["Bold", "Flexible", "Pattern", "Long"], duration: 2450, play: Presets.lament },
  { name: "Latch", description: "The clear feel of something switching off.", tags: ["Substantial", "Flexible", "Bumps", "Short"], duration: 230, play: Presets.latch },
  { name: "Lighthouse", description: "Steady and bias-free.", tags: ["Substantial", "Flexible", "Pattern", "Long"], duration: 1050, play: Presets.lighthouse },
  { name: "Lilt", description: "Warm and personal.", tags: ["Substantial", "Flexible", "Bumps", "Extended"], duration: 360, play: Presets.lilt },
  { name: "Lock", description: "The satisfying click of locking into place.", tags: ["Substantial", "Flexible", "Bumps", "Short"], duration: 220, play: Presets.lock },
  { name: "Lope", description: "A galloping bounce with swagger.", tags: ["Substantial", "Rigid", "Pattern", "Extended"], duration: 450, play: Presets.lope },
  { name: "March", description: "Like an encouraging pat on the back.", tags: ["Substantial", "Soft", "Bumps", "Long"], duration: 900, play: Presets.march },
  { name: "Metronome", description: "Balanced and unemotional.", tags: ["Substantial", "Flexible", "Impulses", "Extended"], duration: 280, play: Presets.metronome },
  { name: "Murmur", description: "Two soft, quiet taps.", tags: ["Substantial", "Soft", "Impulses", "Impulse"], duration: 80, play: Presets.murmur },
  { name: "Nudge", description: "A polite, unobtrusive double tap.", tags: ["Substantial", "Flexible", "Bumps", "Short"], duration: 180, play: Presets.nudge },
  { name: "PassingCar", description: "The whoosh of something passing at speed.", tags: ["Bold", "Flexible", "Peak", "Long"], duration: 1100, play: Presets.passingCar },
  { name: "Patter", description: "Three mild, unforced taps.", tags: ["Substantial", "Soft", "Impulses", "Short"], duration: 179, play: Presets.patter },
  { name: "Peal", description: "Firm and measured.", tags: ["Bold", "Flexible", "Bumps", "Extended"], duration: 438, play: Presets.peal },
  { name: "Peck", description: "An ultra-short, precise tap.", tags: ["Gentle", "Flexible", "Peak", "Impulse"], duration: 28, play: Presets.peck },
  { name: "Pendulum", description: "A rhythmic swing that gradually settles.", tags: ["Substantial", "Flexible", "Bumps", "Long"], duration: 2400, play: Presets.pendulum },
  { name: "Ping", description: "A precise, definitive click.", tags: ["Substantial", "Rigid", "Impulses", "Impulse"], duration: 35, play: Presets.ping },
  { name: "Pip", description: "A light, sparkling burst.", tags: ["Gentle", "Rigid", "Impulses", "Impulse"], duration: 100, play: Presets.pip },
  { name: "Piston", description: "Two forceful, immediate strikes.", tags: ["Bold", "Flexible", "Impulses", "Impulse"], duration: 73, play: Presets.piston },
  { name: "Plink", description: "A neutral heads-up.", tags: ["Substantial", "Flexible", "Bumps", "Short"], duration: 215, play: Presets.plink },
  { name: "Plummet", description: "The terrifying pause before impact.", tags: ["Bold", "Soft", "Peak", "Long"], duration: 1050, play: Presets.plummet },
  { name: "Plunk", description: "Understated but present.", tags: ["Substantial", "Soft", "Impulses", "Impulse"], duration: 0, play: Presets.plunk },
  { name: "Poke", description: "Someone specifically called your name.", tags: ["Substantial", "Flexible", "Bumps", "Extended"], duration: 280, play: Presets.poke },
  { name: "Pound", description: "Impossible to ignore.", tags: ["Bold", "Rigid", "Bumps", "Extended"], duration: 265, play: Presets.pound },
  { name: "PowerDown", description: "A steady deceleration to silence.", tags: ["Bold", "Flexible", "Ramp", "Long"], duration: 1800, play: Presets.powerDown },
  { name: "Propel", description: "A confident forward push.", tags: ["Bold", "Flexible", "Bumps", "Extended"], duration: 300, play: Presets.propel },
  { name: "Pulse", description: "A gentle, steady pulse.", tags: ["Gentle", "Flexible", "Bumps", "Long"], duration: 2000, play: Presets.pulse },
  { name: "Pummel", description: "Escalating rage that peaks at full force.", tags: ["Bold", "Rigid", "Saw", "Extended"], duration: 450, play: Presets.pummel },
  { name: "Push", description: "A quieter click that supports without competing.", tags: ["Gentle", "Flexible", "Peak", "Impulse"], duration: 90, play: Presets.push },
  { name: "Radar", description: "The focused sweep of active scanning.", tags: ["Substantial", "Flexible", "Pattern", "Long"], duration: 2520, play: Presets.radar },
  { name: "Rain", description: "Soft and unpredictable.", tags: ["Gentle", "Flexible", "Pattern", "Long"], duration: 950, play: Presets.rain },
  { name: "Ramp", description: "The joy of growing stronger.", tags: ["Bold", "Rigid", "Bumps", "Long"], duration: 650, play: Presets.ramp },
  { name: "Rap", description: "A clean double-knock.", tags: ["Substantial", "Flexible", "Bumps", "Short"], duration: 120, play: Presets.rap },
  { name: "Ratchet", description: "A firm, assertive triple beat.", tags: ["Bold", "Rigid", "Impulses", "Extended"], duration: 398, play: Presets.ratchet },
  { name: "Rebound", description: "A strong opening that softens on the second hit.", tags: ["Bold", "Rigid", "Impulses", "Impulse"], duration: 80, play: Presets.rebound },
  { name: "Ripple", description: "A strong hit that radiates outward in softening waves.", tags: ["Bold", "Flexible", "Bumps", "Extended"], duration: 420, play: Presets.ripple },
  { name: "Rivet", description: "Three sharp, assertive beats.", tags: ["Bold", "Rigid", "Impulses", "Short"], duration: 150, play: Presets.rivet },
  { name: "Rustle", description: "A gentle heads-up.", tags: ["Substantial", "Flexible", "Bumps", "Extended"], duration: 290, play: Presets.rustle },
  { name: "Shockwave", description: "The pressure wave of a nearby explosion.", tags: ["Bold", "Flexible", "Ramp", "Long"], duration: 800, play: Presets.shockwave },
  { name: "Snap", description: "A firm snap that conveys a locked-in selection.", tags: ["Substantial", "Flexible", "Impulses", "Impulse"], duration: 90, play: Presets.snap },
  { name: "Sonar", description: "The eureka moment.", tags: ["Bold", "Rigid", "Pattern", "Long"], duration: 2000, play: Presets.sonar },
  { name: "Spark", description: "The snap of electric ignition.", tags: ["Bold", "Rigid", "Peak", "Short"], duration: 185, play: Presets.spark },
  { name: "Spin", description: "A crisp, mechanical rhythm.", tags: ["Substantial", "Flexible", "Saw", "Long"], duration: 1808, play: Presets.spin },
  { name: "Stagger", description: "Woozy and disorienting.", tags: ["Substantial", "Flexible", "Saw", "Extended"], duration: 320, play: Presets.stagger },
  { name: "Stamp", description: "Calm and decisive.", tags: ["Substantial", "Soft", "Impulses", "Short"], duration: 205, play: Presets.stamp },
  { name: "Stampede", description: "Four deep, measured thumps.", tags: ["Bold", "Soft", "Impulses", "Long"], duration: 750, play: Presets.stampede },
  { name: "Stomp", description: "Three deep, grounded beats.", tags: ["Bold", "Soft", "Impulses", "Short"], duration: 150, play: Presets.stomp },
  { name: "StoneSkip", description: "Three firm taps with a softening finish.", tags: ["Bold", "Flexible", "Impulses", "Short"], duration: 181, play: Presets.stoneSkip },
  { name: "Strike", description: "A confident, decisive strike.", tags: ["Substantial", "Flexible", "Peak", "Impulse"], duration: 80, play: Presets.strike },
  { name: "Summon", description: "A commanding signal that refuses to be ignored.", tags: ["Bold", "Flexible", "Bumps", "Extended"], duration: 500, play: Presets.summon },
  { name: "Surge", description: "An irrepressible swell of delight.", tags: ["Bold", "Rigid", "Saw", "Extended"], duration: 330, play: Presets.surge },
  { name: "Sway", description: "Reassuring and rhythmic.", tags: ["Substantial", "Soft", "Bumps", "Long"], duration: 1900, play: Presets.sway },
  { name: "Sweep", description: "The rhythmic pulse of active searching.", tags: ["Substantial", "Rigid", "Pattern", "Long"], duration: 2100, play: Presets.sweep },
  { name: "Swell", description: "A patient nudge that quietly escalates.", tags: ["Substantial", "Flexible", "Bumps", "Extended"], duration: 425, play: Presets.swell },
  { name: "Syncopate", description: "A lively three-beat rhythm.", tags: ["Bold", "Rigid", "Impulses", "Extended"], duration: 399, play: Presets.syncopate },
  { name: "Throb", description: "An accelerated heartbeat.", tags: ["Substantial", "Flexible", "Impulses", "Short"], duration: 230, play: Presets.throb },
  { name: "Thud", description: "A soft, warm acknowledgement.", tags: ["Substantial", "Flexible", "Peak", "Short"], duration: 160, play: Presets.thud },
  { name: "Thump", description: "Confident and present without being harsh.", tags: ["Bold", "Flexible", "Impulses", "Impulse"], duration: 0, play: Presets.thump },
  { name: "Thunder", description: "The raw power of a thunderstorm.", tags: ["Bold", "Soft", "Peak", "Long"], duration: 2000, play: Presets.thunder },
  { name: "ThunderRoll", description: "A dramatic arc of mounting intensity.", tags: ["Bold", "Flexible", "Impulses", "Long"], duration: 670, play: Presets.thunderRoll },
  { name: "TickTock", description: "The steady pulse of time.", tags: ["Bold", "Flexible", "Pattern", "Long"], duration: 1200, play: Presets.tickTock },
  { name: "TidalSurge", description: "Two waves of escalating intensity.", tags: ["Bold", "Flexible", "Impulses", "Extended"], duration: 455, play: Presets.tidalSurge },
  { name: "TideSwell", description: "A long wave-like arc that rises and falls.", tags: ["Substantial", "Flexible", "Impulses", "Long"], duration: 727, play: Presets.tideSwell },
  { name: "Tremor", description: "Pure, heavy rumble with no sharpness.", tags: ["Bold", "Soft", "Impulses", "Impulse"], duration: 0, play: Presets.tremor },
  { name: "Trigger", description: "The decisive moment of release.", tags: ["Bold", "Flexible", "Peak", "Extended"], duration: 280, play: Presets.trigger },
  { name: "Triumph", description: "Pure triumph.", tags: ["Bold", "Flexible", "Saw", "Long"], duration: 1100, play: Presets.triumph },
  { name: "Trumpet", description: "A joyful flourish that peaks in triumph.", tags: ["Bold", "Flexible", "Saw", "Extended"], duration: 460, play: Presets.trumpet },
  { name: "Typewriter", description: "The nostalgic thud of a vintage typewriter.", tags: ["Bold", "Flexible", "Peak", "Short"], duration: 200, play: Presets.typewriter },
  { name: "Unfurl", description: "The unmistakable thrill of discovery.", tags: ["Bold", "Flexible", "Pattern", "Long"], duration: 1180, play: Presets.unfurl },
  { name: "Vortex", description: "An irresistible pull into the unknown.", tags: ["Substantial", "Flexible", "Peak", "Long"], duration: 1400, play: Presets.vortex },
  { name: "Wane", description: "A lazy, dismissive fade.", tags: ["Gentle", "Flexible", "Ramp", "Extended"], duration: 450, play: Presets.wane },
  { name: "WarDrum", description: "Three steady drum-like beats.", tags: ["Bold", "Soft", "Impulses", "Extended"], duration: 398, play: Presets.warDrum },
  { name: "Waterfall", description: "A rush of energy that spills and softens.", tags: ["Bold", "Flexible", "Impulses", "Extended"], duration: 309, play: Presets.waterfall },
  { name: "Wave", description: "Gentle and uninterrupting.", tags: ["Substantial", "Soft", "Bumps", "Long"], duration: 2800, play: Presets.wave },
  { name: "Wisp", description: "A barely-there touch.", tags: ["Gentle", "Flexible", "Peak", "Impulse"], duration: 60, play: Presets.wisp },
  { name: "Wobble", description: "A gentle correction without alarm.", tags: ["Substantial", "Rigid", "Peak", "Short"], duration: 180, play: Presets.wobble },
  { name: "Woodpecker", description: "Mechanical and relentless.", tags: ["Bold", "Rigid", "Solid", "Extended"], duration: 460, play: Presets.woodpecker },
  { name: "Zipper", description: "The familiar drag and snap of a zipper closing.", tags: ["Gentle", "Flexible", "Solid", "Extended"], duration: 460, play: Presets.zipper },
];

// Original app hides system presets by default (behind a toggle in Filters Modal).
// Show only custom presets in the main list to match the original behavior.
export const ALL_PRESETS = CUSTOM_PRESETS;
